apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawkbit-fota
spec:
  selector:
    matchLabels:
      app: hawkbit
  template:
    metadata:
      labels:
        app: hawkbit
    spec:
      containers:
      - name: hawkbitfota
        image: jonathanyhliang/hawkbit-fota:latest
        command:
        - /bin/sh
        - "-c"
        - "./build/cli -f :8080 -b :8081"
        ports:
        - containerPort: 8080
          name: hawkbit-front
        - containerPort: 8081
          name: hawkbit-back

---
apiVersion: v1
kind: Service
metadata:
  name: hawkbit-service
spec:
  type: NodePort
  selector:
    app: hawkbit
  ports:
  - name: hawkbit-service-front
    protocol: TCP
    port: 8080
    targetPort: hawkbit-front
  - name: hawkbit-service-back
    protocol: TCP
    port: 8081
    targetPort: hawkbit-back
