apiVersion: apps/v1
kind: Deployment
metadata:
  name: slcan
spec:
  selector:
    matchLabels:
      app: slcan
  template:
    metadata:
      labels:
        app: slcan
    spec:
      containers:
      - name: slcansvc
        image: jonathanyhliang/slcan-svc:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-svc-rabbitmq-default-user
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-svc-rabbitmq-default-user
              key: password
        command:
        - /bin/sh
        - "-c"
        - "socat pty,link=/dev/vmodem0,waitslave,ignoreeof tcp:host.minikube.internal:80 \
           & ./build/cli -p /dev/vmodem0 \
                         -u amqp://$USERNAME:$PASSWORD@demo-svc-rabbitmq:5672/"
        ports:
        - containerPort: 8080
          name: slcan-pod-front
      - name: mcumgrsvc
        image: jonathanyhliang/mcumgr-svc:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-svc-rabbitmq-default-user
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-svc-rabbitmq-default-user
              key: password
        command:
        - /bin/sh
        - "-c"
        - "socat pty,link=/dev/vmodem0.waitslave,ignoreeof tcp:host.minikube.internal:80 \
           & ./mcumgr-svc -bid slcan-1234 \
                          -s hawkbit-service:8081 \
                          -p /dev/vmodem0 \
                          -u amqp://$USERNAME:$PASSWORD@demo-svc-rabbitmq:5672/"

---
apiVersion: v1
kind: Service
metadata:
  name: slcan-service
spec:
  selector:
    label: slcan
  ports:
  - name: slcan-service-port
    protocol: TCP
    port: 8082
    targetPort: slcan-svc-front
