@startuml demo-svc
nwdiag {

  group slcan {
    color = "#FFAAAA";
    slcan-svc
    slcan-socat-client
  }
  group mcumgr {
    color = "#FFAAAA";
    mcumgr-svc
    mcumgr-socat-client
  }
  network host-machine {
    color = "red"
    ingress-controller [address = "http://demo.svc                           ", shape = node]
    port-forward [address = "host.minikube.internal:/port                                             "]
  }
  network http {
    color = "palegreen"
    hawkbit-frontend [address = "/fota/hawkbit                        ", shape = node]
    hawkbit-backend [address = """, shape = node]
    slcan-svc [address = "/wired/slcan                      "]
    mcumgr-svc
    ingress-controller
    port-forward
  }
  network amqp {
    slcan-svc [address = "Sender ", shape = node]
    mcumgr-svc [address = "Receiver ", shape = node]
    rabbit-mq [shape = node ]
  }
  network tty-socat {
    slcan-svc [address = "/dev/vmodem                        "]
    mcumgr-svc [address = "/dev/vmodem                        "]
    slcan-socat-client [, shape = node]
    mcumgr-socat-client [, shape = node]
  }
  network tcp-minikube {
    color = "palegreen"
    slcan-socat-client
    mcumgr-socat-client
    socat-server [, shape = node]
  }
  network usb-host-machine {
    color = "red"
    socat-server
    slcan-dev [address = "/dev/ttyACMx                          ", shape = node]
  }
}
@enduml
