@startuml
nwdiag {

  group slcan {
    color = "#FFAAAA";
    SLCAN-svc
    SLCAN-socat-client
  }
  group mcumgr {
    color = "#FFAAAA";
    MCUmgr-svc
    MCUmgr-socat-client
  }
  network host-machine {
    color = "red"
    Ingress-controller [address = "http://demo.svc                           ", shape = node]
  }
  network http-node {
    color = "red"
    Hawkbit-frontend [address = "/fota/hawkbit                        ", shape = node]
    Hawkbit-backend [address = """, shape = node]
    SLCAN-svc [address = "/wired/slcan                      "]
    MCUmgr-svc
    Ingress-controller
  }
  network amqp {
    color = "palegreen"
    SLCAN-svc [address = "Sender ", shape = node]
    MCUmgr-svc [address = "Receiver ", shape = node]
    RabbitMQ [address = ":5672            ", shape = node ]
  }
  network tty-socat {
    SLCAN-svc [address = "/dev/vmodem                        "]
    MCUmgr-svc [address = "/dev/vmodem                        "]
    SLCAN-socat-client [, shape = node]
    MCUmgr-socat-client [, shape = node]
  }
  network tcp-minikube {
    SLCAN-socat-client
    MCUmgr-socat-client
    socat-server [, shape = node]
  }
  network usb-host-machine {
    socat-server
    SLCAN-dev [address = "/dev/ttyACMx                          ", shape = node]
  }
}
@enduml
