@startuml
nwdiag {
  group nightly {
    color = "#FFAAAA";
    MCUmgr-svc
    RabbitMQ
  }
  network http {
    address = "localhost"
    color = "red"
    SLCAN-svc [address = ":8080           "]
    MCUmgr-svc [address = ":8081          "]
  }
  network amqp {
    address = "localhost"
    color = "palegreen"
    SLCAN-svc [address = "Sender ", shape = node]
    MCUmgr-svc [address = "Receiver ",shape = node]
    RabbitMQ [address = ":5672            ", shape = node ]
  }
  network tty {
    SLCAN-svc
    MCUmgr-svc
    COM [shape = node]
  }
}
@enduml


@startuml timing
SLCAN -> MCUmgr: Authentication Request
MCUmgr --> SLCAN: Authentication Response

SLCAN -> MCUmgr: Another authentication Request
SLCAN <-- MCUmgr: Another authentication Response
@enduml
